name: kashima
description: Mobile version of Kashima made in Flutter
version: 1.0.0-alpha.0
environment:
  sdk: ">=2.6.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  provider: ^4.0.5+1
  path_provider: ^1.6.7
  flutter_dotenv: ^2.1.0
  tuple: ^1.0.3
  custom_splash: ^0.0.2
  flute_music_player: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
assets:
  - .env